name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Change to Client Directory
        run: cd client

      - name: Install Client Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Build Client
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Test Client
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Server Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Build Server
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Test Serverr
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

  build-db:
    needs: [build-client, build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install MySQL
        uses: actions/setup-mysql@v2
        with:
          mysql-version: "8.0"

      - name: Start MySQL
        run: sudo service mysql start

      - name: Import SQL file
        run: mysql -u root -p < /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/database/lorem.sql

      - name: Populate Tables
        run: python /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server/database/populate_tables.py
