name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # - name: Use MySQL
      #   uses: shogo82148/actions-setup-mysql@v1
      #   with:
      #     mysql-version: "8.0"
      # - run: mysql -uroot -e 'SELECT version()'

      - name: Install Client Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Build Client
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Start Client
        run: npm start &
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Start SQL Service
        run: sudo /etc/init.d/mysql start

      - name: Import SQL file
        run: mysql -u root -p"root" < /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/database/lorem.sql

      - name: Install pip package
        run: pip install mysql-connector-python

      - name: Populate Tables
        run: python ./populate_tables.py
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/database

      - name: Install Server Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Build Server
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Allow connection
        run: sudo ufw allow 3306

      - name: Start Server
        run: npm start &
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      # - name: Wait a moment
      #   run: sleep 10

      - name: Test Server
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Test Client
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client
