name: Node.js CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: <span class="math-inline">\{\{ runner\.os \}\}\-npm\-</span>{{ hashFiles('**/package-lock.json') }}

      - name: Change to Client Directory
        run: cd client

      - name: Install Client Dependencies
        run: npm install --if-present
        working-directory: ./client

      - name: Build Client
        run: npm run build --if-present
        working-directory: ./client

      - name: Test Client
        run: npm test
        working-directory: ./client

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cache Node.js dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: <span class="math-inline">\{\{ runner\.os \}\}\-npm\-</span>{{ hashFiles('**/package-lock.json') }}

      - name: Change to Server Directory
        run: cd server

      - name: Install Server Dependencies
        run: npm install --if-present
        working-directory: ./server

      - name: Build Server
        run: npm run build --if-present
        working-directory: ./server

      - name: Test Server
        run: npm test
        working-directory: ./server

  build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MySQL
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: Check MySQL version
        run: mysql -uroot -e 'SELECT version()'

      - name: Import SQL file
        run: mysql -u root -p < ./database/lorem.sql

  test-db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.0", "3.9.0", "3.10.0", "3.11.0", "3.12.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test DB
        run: python test_db.py
