name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Change to Client Directory
        run: cd client

      - name: Install Client Dependencies
        run: npm ci

      - name: Build Client
        run: npm run build --if-present

      - name: Test Client
        run: npm test

