name: Node.js CI

on: 
  push:
    paths:
      - 'client/**'
      - '.github/**'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'server/**'
    branches:
      - 'main'

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client:
            - 'client/**'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Change to Client Directory
        run: cd client

      - name: Install Client Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Build Client
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

      - name: Test Client
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/client

  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
            - 'server/**'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Server Dependencies
        run: npm ci
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Build Server
        run: npm run build --if-present
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server

      - name: Test Serverr
        run: npm test
        working-directory: /home/runner/work/0verdrive-soen341projectF2023/0verdrive-soen341projectF2023/server
