name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          
      - name: Change to Client Directory
        run: cd client
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test


