name: Lint

on: [push]
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - "main"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ESLint
        run: server/node_modules/eslint/bin/eslint.js ./ --ext .js,.jsx
